backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - label: "DER FILM",
            name: "the_movie",
            widget: "object",
            collapsed: true
            fields:
              - label: "Beschreibung",
                name: "section_description",
                widget: "list",
                fields:
                  - { label: "Deutsch", name: "text_block_de", widget: "markdown" },
                  - { label: "Französisch", name: "text_block_fr", widget: "markdown" },
