backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - label: "DER FILM"
            name: "the_movie"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Film Trailer",
                  name: "movie_trailer",
                  widget: "string",
                }
              - label: "Beschreibung"
                name: "section_description"
                widget: "list"
                fields:
                  - {
                      label: "Deutsch",
                      name: "text_block_de",
                      widget: "markdown",
                    }
                  - {
                      label: "Französisch",
                      name: "text_block_fr",
                      widget: "markdown",
                    }
          - label: "DIE PREMIERE"
            name: "the_premiere"
            widget: "object"
            collapsed: true
            fields:
              - label: "Infokarte"
                name: "info_card"
                widget: "object"
                collapsed: true
                fields:
                  - label: "Premieren Titel"
                    name: "premiere_title"
                    widget: "object"
                    collapsed: true
                    fields:
                      - {
                          label: "Titel Deutsch",
                          name: "title_de",
                          widget: "string",
                        }
                      - {
                          label: "Titel Französisch",
                          name: "title_fr",
                          widget: "string",
                        }
                      - {
                          label: "Zoom Link Titel Deutsch",
                          name: "zoom_link_title_de",
                          widget: "string",
                        }
                      - {
                          label: "Zoom Link Titel Französisch",
                          name: "zoom_link_title_fr",
                          widget: "string",
                        }
                      - {
                          label: "Zoom Link",
                          name: "zoom_link",
                          widget: "string",
                        }
                  - label: "Ablaufplan"
                    name: "schedule"
                    widget: "list"
                    fields:
                      - { label: "Zeit", name: "time", widget: "string" }
                      - { label: "Ablauf", name: "procedure", widget: "string" }
